"use client";
import React from "react";

interface DocumentFooterProps {
  email: string;
  website: string;
  address: string;
  pageNum?: number;
  totalPages?: number;
}

export default function DocumentFooter({ email, website, address, pageNum, totalPages }: DocumentFooterProps) {
  return (
    <footer className="z-10 px-10 pb-6 pt-3 border-t border-slate-300 text-[12px] text-slate-400 font-mono flex flex-col justify-center">
      <div className="flex justify-between">
        <span>
          Generated by:{" "}
          <strong className="text-indigo-600">HR Document Engine by JEVXO</strong>
        </span>
        {pageNum !== undefined && totalPages !== undefined && (
          <span>Page {pageNum} of {totalPages}</span>
        )}
        <div className="flex gap-6">
          <span>
            Email: <strong className="text-slate-600 font-semibold">{email}</strong>
          </span>
          <span>
            Website: <strong className="text-slate-600 font-semibold">{website}</strong>
          </span>
        </div>
      </div>
      <span className="text-center">
        <strong className="text-slate-600 font-semibold">{address}</strong>
      </span>
    </footer>
  );
}
